function datasetout = importmeasurements(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as a dataset
%   array.
%
%   IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Date formatted cells are converted to MATLAB serial date number format
%	(datenum).
%
% Example:
%   importfile('kens_measurements.xlsx','Sheet1',2,14);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/07/02 14:32:36

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 14;
end

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
[~, ~, raw1, dateNums1] = xlsread(workbookFile, sheetName, sprintf('A%d:A%d',startRow(1),endRow(1)),'' , @convertSpreadsheetDates);
[~, ~, raw2, dateNums2] = xlsread(workbookFile, sheetName, sprintf('D%d:E%d',startRow(1),endRow(1)),'' , @convertSpreadsheetDates);
raw = [raw1,raw2];
dateNums = [dateNums1,dateNums2];
for block=2:length(startRow)
    [~, ~, tmpRawBlock1, tmpDateNumBlock1] = xlsread(workbookFile, sheetName, sprintf('A%d:A%d',startRow(block),endRow(block)),'' , @convertSpreadsheetDates);
    [~, ~, tmpRawBlock2, tmpDateNumBlock2] = xlsread(workbookFile, sheetName, sprintf('D%d:E%d',startRow(block),endRow(block)),'' , @convertSpreadsheetDates);
    raw = [raw;tmpRawBlock1,tmpRawBlock2]; %#ok<AGROW>
    dateNums = [dateNums;tmpDateNumBlock1,tmpDateNumBlock2]; %#ok<AGROW>
end

%% Replace date strings by MATLAB serial date numbers (datenum)
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
raw(R) = dateNums(R);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create dataset array
datasetout = dataset;

%% Allocate imported array to column variable names
datasetout.datetime = data(:,1);
datasetout.loc336 = data(:,2);
datasetout.loc338 = data(:,3);

